### ISSUE TITLE
Need rc branch to submit PR into.

### ISSUE THREAD

**Issue by jcannon-gplates** [conda-forge/pygplates-feedstock#30]
Hi,

Can an admin create an `rc` branch?

I'm releasing `1.0.0rc1`, but according to the [docs](https://conda-forge.org/docs/maintainer/knowledge_base/#creating-a-pre-release-build) I need to submit a PR into the `rc` branch (which I don't have permission to create).

cc @h-vetinari 

Thanks,
John

**Comment by h-vetinari** [comment]
Branch `rc` has been created. Please add the following in `recipe/conda_build_config.yaml` in your PR before you rerender:
```yaml
channel_targets:
  - conda-forge gplates_rc  # or any other name specific to this feedstock
```

You'll then be able to reproduce whatever gets produced here by adding `-c conda-forge/label/gplates_rc` to your install invocation.

**Comment by jcannon-gplates** [comment]
Great, thanks very much!
